### PR TITLE
Delete Resources

### PR DESCRIPTION
**Pull request by tekanaid**
Need to delete VM

### CODE REVIEW

**Comment by samgabrail** [comment]
Ran Plan for dir: `.` workspace: `default`

```diff
google_compute_instance.default: Refreshing state... [id=projects/terraformprojects-365816/zones/us-central1-a/instances/atlantis-vm-dev]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration
and found no differences, so no changes are needed.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://6cf5-20-232-211-174.ngrok.io/lock?id=samgabrail%252Fenv0-atlantis-gcp%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by tekanaid** [comment]
atlantis destroy

**Comment by samgabrail** [comment]
```
Error: unknown command "destroy".
Run 'atlantis --help' for usage.
Available commands(--allow-commands): version, plan, apply, unlock, approve_policies
```

**Comment by tekanaid** [comment]
atlantis --help

**Comment by samgabrail** [comment]
```cmake
atlantis
Terraform Pull Request Automation

Usage:
  atlantis <command> [options] -- [terraform options]

Examples:
  # show atlantis help
  atlantis help

  # run plan in the root directory passing the -target flag to terraform
  atlantis plan -d . -- -target=resource

  # apply all unapplied plans from this pull request
  atlantis apply

  # apply the plan for the root directory and staging workspace
  atlantis apply -d . -w staging

Commands:
  plan     Runs 'terraform plan' for the changes in this pull request.
           To plan a specific project, use the -d, -w and -p flags.
  apply    Runs 'terraform apply' on all unapplied plans from this pull request.
           To only apply a specific plan, use the -d, -w and -p flags.
  unlock   Removes all atlantis locks and discards all plans for this PR.
           To unlock a specific plan you can use the Atlantis UI.
  approve_policies
           Approves all current policy checking failures for the PR.
  version  Print the output of 'terraform version'
  help     View help.

Flags:
  -h, --help   help for atlantis

Use "atlantis [command] --help" for more information about a command.
```

**Comment by tekanaid** [comment]
atlantis plan -destroy

**Comment by samgabrail** [comment]
Ran Plan for dir: `estroy` workspace: `default`

**Plan Error**
```
dir "estroy" does not exist
```

**Comment by tekanaid** [comment]
atlantis plan -- -destroy

**Comment by samgabrail** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
google_compute_instance.default: Refreshing state... [id=projects/terraformprojects-365816/zones/us-central1-a/instances/atlantis-vm-dev]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # google_compute_instance.default will be destroyed
- resource "google_compute_instance" "default" {
      - can_ip_forward       = false -> null
      - cpu_platform         = "Intel Broadwell" -> null
      - current_status       = "RUNNING" -> null
      - deletion_protection  = false -> null
      - enable_display       = false -> null
      - guest_accelerator    = [] -> null
      - id                   = "projects/terraformprojects-365816/zones/us-central1-a/instances/atlantis-vm-dev" -> null
      - instance_id          = "4661442100994193029" -> null
      - label_fingerprint    = "42WmSpB8rSM=" -> null
      - labels               = {} -> null
      - machine_type         = "e2-micro" -> null
      - metadata             = {} -> null
      - metadata_fingerprint = "OunhsVn_J1I=" -> null
      - name                 = "atlantis-vm-dev" -> null
      - project              = "terraformprojects-365816" -> null
      - resource_policies    = [] -> null
      - self_link            = "https://www.googleapis.com/compute/v1/projects/terraformprojects-365816/zones/us-central1-a/instances/atlantis-vm-dev" -> null
      - tags                 = [
          - "dev",
          - "engineering",
        ] -> null
      - tags_fingerprint     = "x7YZUfmdF48=" -> null
      - zone                 = "us-central1-a" -> null

      - boot_disk {
          - auto_delete = true -> null
          - device_name = "persistent-disk-0" -> null
          - mode        = "READ_WRITE" -> null
          - source      = "https://www.googleapis.com/compute/v1/projects/terraformprojects-365816/zones/us-central1-a/disks/atlantis-vm-dev" -> null

          - initialize_params {
              - image  = "https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20221014" -> null
              - labels = {
                  - "env" = "dev"
                } -> null
              - size   = 10 -> null
              - type   = "pd-standard" -> null
            }
        }

      - network_interface {
          - name               = "nic0" -> null
          - network            = "https://www.googleapis.com/compute/v1/projects/terraformprojects-365816/global/networks/default" -> null
          - network_ip         = "10.128.0.12" -> null
          - queue_count        = 0 -> null
          - stack_type         = "IPV4_ONLY" -> null
          - subnetwork         = "https://www.googleapis.com/compute/v1/projects/terraformprojects-365816/regions/us-central1/subnetworks/default" -> null
          - subnetwork_project = "terraformprojects-365816" -> null

          - access_config {
              - nat_ip       = "34.121.17.154" -> null
              - network_tier = "PREMIUM" -> null
            }
        }

      - scheduling {
          - automatic_restart   = true -> null
          - min_node_cpus       = 0 -> null
          - on_host_maintenance = "MIGRATE" -> null
          - preemptible         = false -> null
          - provisioning_model  = "STANDARD" -> null
        }

      - shielded_instance_config {
          - enable_integrity_monitoring = true -> null
          - enable_secure_boot          = false -> null
          - enable_vtpm                 = true -> null
        }
    }

Plan: 0 to add, 0 to change, 1 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://6cf5-20-232-211-174.ngrok.io/lock?id=samgabrail%252Fenv0-atlantis-gcp%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d . -- -destroy`
</details>
Plan: 0 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by tekanaid** [comment]
atlantis plan -destroy

**Comment by samgabrail** [comment]
Ran Plan for dir: `estroy` workspace: `default`

**Plan Error**
```
dir "estroy" does not exist
```

**Pull request closed without merging**
