### PR TITLE
Launch

### PR DESCRIPTION
**Pull request by tekanaid**

### CODE REVIEW

**Comment by tekanaid** [comment]
atlantis plan

**Comment by tekanaid** [comment]
atlantis apply -d .

**Comment by samgabrail** [comment]
Ran Apply for dir: `.` workspace: `default`

```diff
google_compute_instance.default: Creating...
google_compute_instance.default: Still creating... [10s elapsed]
google_compute_instance.default: Creation complete after 12s [id=projects/terraformprojects-365816/zones/us-central1-a/instances/atlantis-vm-dev]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

**Review by samgabrail — APPROVED** [review]
approved

**Comment by samgabrail** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Review by tekanaid — COMMENTED** [review]
destroy

**Pull request merged**
