### PR TITLE
launch

### PR DESCRIPTION
**Pull request by tekanaid**

### CODE REVIEW

**Comment by samgabrail** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # google_compute_instance.default will be created
+ resource "google_compute_instance" "default" {
      + can_ip_forward       = false
      + cpu_platform         = (known after apply)
      + current_status       = (known after apply)
      + deletion_protection  = false
      + guest_accelerator    = (known after apply)
      + id                   = (known after apply)
      + instance_id          = (known after apply)
      + label_fingerprint    = (known after apply)
      + machine_type         = "e2-micro"
      + metadata_fingerprint = (known after apply)
      + min_cpu_platform     = (known after apply)
      + name                 = "atlantis-vm-dev"
      + project              = (known after apply)
      + self_link            = (known after apply)
      + tags                 = [
          + "dev",
          + "engineering",
        ]
      + tags_fingerprint     = (known after apply)
      + zone                 = "us-central1-a"

      + boot_disk {
          + auto_delete                = true
          + device_name                = (known after apply)
          + disk_encryption_key_sha256 = (known after apply)
          + kms_key_self_link          = (known after apply)
          + mode                       = "READ_WRITE"
          + source                     = (known after apply)

          + initialize_params {
              + image  = "projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20221014"
              + labels = {
                  + "env" = "dev"
                }
              + size   = (known after apply)
              + type   = (known after apply)
            }
        }

      + network_interface {
          + ipv6_access_type   = (known after apply)
          + name               = (known after apply)
          + network            = "default"
          + network_ip         = (known after apply)
          + stack_type         = (known after apply)
          + subnetwork         = (known after apply)
          + subnetwork_project = (known after apply)

          + access_config {
              + nat_ip       = (known after apply)
              + network_tier = (known after apply)
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://b3c4-13-82-2-162.ngrok-free.app/lock?id=samgabrail%252Fenv0-atlantis-gcp%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by tekanaid** [comment]
atlantis apply

**Comment by samgabrail** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
google_compute_instance.default: Refreshing state... [id=projects/terraformprojects-365816/zones/us-central1-a/instances/atlantis-vm-dev]

Changes to Outputs:
+ hostname          = ""
+ instance_id       = "2979553188716095310"
+ network_interface = [
      + {
          + access_config      = [
              + {
                  + nat_ip                 = "34.30.237.205"
                  + network_tier           = "PREMIUM"
                  + public_ptr_domain_name = ""
                },
            ]
          + alias_ip_range     = []
          + ipv6_access_config = []
          + ipv6_access_type   = ""
          + name               = "nic0"
          + network            = "https://www.googleapis.com/compute/v1/projects/terraformprojects-365816/global/networks/default"
          + network_ip         = "10.128.0.14"
          + nic_type           = ""
          + queue_count        = 0
          + stack_type         = "IPV4_ONLY"
          + subnetwork         = "https://www.googleapis.com/compute/v1/projects/terraformprojects-365816/regions/us-central1/subnetworks/default"
          + subnetwork_project = "terraformprojects-365816"
        },
    ]

You can apply this plan to save these new output values to the Terraform
state, without changing any real infrastructure.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://b3c4-13-82-2-162.ngrok-free.app/lock?id=samgabrail%252Fenv0-atlantis-gcp%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Review by samgabrail — APPROVED** [review]
all is good

**Comment by samgabrail** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
