### PR TITLE
Now delete

### PR DESCRIPTION
**Pull request by tekanaid**

### CODE REVIEW

**Comment by samgabrail** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
google_compute_instance.default: Refreshing state... [id=projects/terraformprojects-365816/zones/us-central1-a/instances/atlantis-vm-dev]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # google_compute_instance.default will be destroyed
  # (because google_compute_instance.default is not in configuration)
- resource "google_compute_instance" "default" {
      - can_ip_forward       = false -> null
      - cpu_platform         = "Intel Broadwell" -> null
      - current_status       = "RUNNING" -> null
      - deletion_protection  = false -> null
      - enable_display       = false -> null
      - guest_accelerator    = [] -> null
      - id                   = "projects/terraformprojects-365816/zones/us-central1-a/instances/atlantis-vm-dev" -> null
      - instance_id          = "907407506220721761" -> null
      - label_fingerprint    = "42WmSpB8rSM=" -> null
      - labels               = {} -> null
      - machine_type         = "e2-micro" -> null
      - metadata             = {} -> null
      - metadata_fingerprint = "OunhsVn_J1I=" -> null
      - name                 = "atlantis-vm-dev" -> null
      - project              = "terraformprojects-365816" -> null
      - resource_policies    = [] -> null
      - self_link            = "https://www.googleapis.com/compute/v1/projects/terraformprojects-365816/zones/us-central1-a/instances/atlantis-vm-dev" -> null
      - tags                 = [
          - "dev",
          - "engineering",
        ] -> null
      - tags_fingerprint     = "x7YZUfmdF48=" -> null
      - zone                 = "us-central1-a" -> null

      - boot_disk {
          - auto_delete = true -> null
          - device_name = "persistent-disk-0" -> null
          - mode        = "READ_WRITE" -> null
          - source      = "https://www.googleapis.com/compute/v1/projects/terraformprojects-365816/zones/us-central1-a/disks/atlantis-vm-dev" -> null

          - initialize_params {
              - image  = "https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20221014" -> null
              - labels = {
                  - "env" = "dev"
                } -> null
              - size   = 10 -> null
              - type   = "pd-standard" -> null
            }
        }

      - network_interface {
          - name               = "nic0" -> null
          - network            = "https://www.googleapis.com/compute/v1/projects/terraformprojects-365816/global/networks/default" -> null
          - network_ip         = "10.128.0.13" -> null
          - queue_count        = 0 -> null
          - stack_type         = "IPV4_ONLY" -> null
          - subnetwork         = "https://www.googleapis.com/compute/v1/projects/terraformprojects-365816/regions/us-central1/subnetworks/default" -> null
          - subnetwork_project = "terraformprojects-365816" -> null

          - access_config {
              - nat_ip       = "35.222.162.5" -> null
              - network_tier = "PREMIUM" -> null
            }
        }

      - scheduling {
          - automatic_restart   = true -> null
          - min_node_cpus       = 0 -> null
          - on_host_maintenance = "MIGRATE" -> null
          - preemptible         = false -> null
          - provisioning_model  = "STANDARD" -> null
        }

      - shielded_instance_config {
          - enable_integrity_monitoring = true -> null
          - enable_secure_boot          = false -> null
          - enable_vtpm                 = true -> null
        }
    }

Plan: 0 to add, 0 to change, 1 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://a2ab-20-120-99-235.ngrok-free.app/lock?id=samgabrail%252Fenv0-atlantis-gcp%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 0 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by tekanaid** [comment]
atlantis plan -- -destroy

**Comment by samgabrail** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
google_compute_instance.default: Refreshing state... [id=projects/terraformprojects-365816/zones/us-central1-a/instances/atlantis-vm-dev]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
- destroy

Terraform will perform the following actions:

  # google_compute_instance.default will be destroyed
- resource "google_compute_instance" "default" {
      - can_ip_forward       = false -> null
      - cpu_platform         = "Intel Broadwell" -> null
      - current_status       = "RUNNING" -> null
      - deletion_protection  = false -> null
      - enable_display       = false -> null
      - guest_accelerator    = [] -> null
      - id                   = "projects/terraformprojects-365816/zones/us-central1-a/instances/atlantis-vm-dev" -> null
      - instance_id          = "907407506220721761" -> null
      - label_fingerprint    = "42WmSpB8rSM=" -> null
      - labels               = {} -> null
      - machine_type         = "e2-micro" -> null
      - metadata             = {} -> null
      - metadata_fingerprint = "OunhsVn_J1I=" -> null
      - name                 = "atlantis-vm-dev" -> null
      - project              = "terraformprojects-365816" -> null
      - resource_policies    = [] -> null
      - self_link            = "https://www.googleapis.com/compute/v1/projects/terraformprojects-365816/zones/us-central1-a/instances/atlantis-vm-dev" -> null
      - tags                 = [
          - "dev",
          - "engineering",
        ] -> null
      - tags_fingerprint     = "x7YZUfmdF48=" -> null
      - zone                 = "us-central1-a" -> null

      - boot_disk {
          - auto_delete = true -> null
          - device_name = "persistent-disk-0" -> null
          - mode        = "READ_WRITE" -> null
          - source      = "https://www.googleapis.com/compute/v1/projects/terraformprojects-365816/zones/us-central1-a/disks/atlantis-vm-dev" -> null

          - initialize_params {
              - image  = "https://www.googleapis.com/compute/v1/projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20221014" -> null
              - labels = {
                  - "env" = "dev"
                } -> null
              - size   = 10 -> null
              - type   = "pd-standard" -> null
            }
        }

      - network_interface {
          - name               = "nic0" -> null
          - network            = "https://www.googleapis.com/compute/v1/projects/terraformprojects-365816/global/networks/default" -> null
          - network_ip         = "10.128.0.13" -> null
          - queue_count        = 0 -> null
          - stack_type         = "IPV4_ONLY" -> null
          - subnetwork         = "https://www.googleapis.com/compute/v1/projects/terraformprojects-365816/regions/us-central1/subnetworks/default" -> null
          - subnetwork_project = "terraformprojects-365816" -> null

          - access_config {
              - nat_ip       = "35.222.162.5" -> null
              - network_tier = "PREMIUM" -> null
            }
        }

      - scheduling {
          - automatic_restart   = true -> null
          - min_node_cpus       = 0 -> null
          - on_host_maintenance = "MIGRATE" -> null
          - preemptible         = false -> null
          - provisioning_model  = "STANDARD" -> null
        }

      - shielded_instance_config {
          - enable_integrity_monitoring = true -> null
          - enable_secure_boot          = false -> null
          - enable_vtpm                 = true -> null
        }
    }

Plan: 0 to add, 0 to change, 1 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://a2ab-20-120-99-235.ngrok-free.app/lock?id=samgabrail%252Fenv0-atlantis-gcp%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d . -- -destroy`
</details>
Plan: 0 to add, 0 to change, 1 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by tekanaid** [comment]
atlantis apply

**Review by samgabrail — APPROVED** [review]
good

**Comment by samgabrail** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
