### PR TITLE
Update main.tf

### PR DESCRIPTION
**Pull request by tekanaid**
deploy

### CODE REVIEW

**Comment by tekanaid** [comment]
terraform plan

**Comment by samgabrail** [comment]
Did you mean to use `atlantis` instead of `terraform`?

**Comment by tekanaid** [comment]
atlantis plan

**Comment by samgabrail** [comment]
Ran Plan for dir: `.` workspace: `default`

**Plan Error**
```
running "/home/codespace/.asdf/shims/terraform init -input=false -upgrade" in "/home/codespace/.atlantis/repos/samgabrail/env0-atlantis-gcp/1/default": exit status 1

Initializing the backend...
╷
│ Error: storage.NewClient() failed: dialing: google: error getting credentials using GOOGLE_APPLICATION_CREDENTIALS environment variable: open gcp-secret-key.json: no such file or directory
│ 
│ 
╵


```

**Comment by tekanaid** [comment]
atlantis plan

**Comment by samgabrail** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
google_compute_instance.default: Refreshing state... [id=projects/terraformprojects-365816/zones/us-central1-a/instances/atlantis-vm-dev]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # google_compute_instance.default will be created
+ resource "google_compute_instance" "default" {
      + can_ip_forward       = false
      + cpu_platform         = (known after apply)
      + current_status       = (known after apply)
      + deletion_protection  = false
      + guest_accelerator    = (known after apply)
      + id                   = (known after apply)
      + instance_id          = (known after apply)
      + label_fingerprint    = (known after apply)
      + machine_type         = "e2-micro"
      + metadata_fingerprint = (known after apply)
      + min_cpu_platform     = (known after apply)
      + name                 = "atlantis-vm-dev"
      + project              = (known after apply)
      + self_link            = (known after apply)
      + tags                 = [
          + "dev",
          + "engineering",
        ]
      + tags_fingerprint     = (known after apply)
      + zone                 = "us-central1-a"

      + boot_disk {
          + auto_delete                = true
          + device_name                = (known after apply)
          + disk_encryption_key_sha256 = (known after apply)
          + kms_key_self_link          = (known after apply)
          + mode                       = "READ_WRITE"
          + source                     = (known after apply)

          + initialize_params {
              + image  = "projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20221014"
              + labels = {
                  + "env" = "dev"
                }
              + size   = (known after apply)
              + type   = (known after apply)
            }
        }

      + network_interface {
          + ipv6_access_type   = (known after apply)
          + name               = (known after apply)
          + network            = "default"
          + network_ip         = (known after apply)
          + stack_type         = (known after apply)
          + subnetwork         = (known after apply)
          + subnetwork_project = (known after apply)

          + access_config {
              + nat_ip       = (known after apply)
              + network_tier = (known after apply)
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://6cf5-20-232-211-174.ngrok.io/lock?id=samgabrail%252Fenv0-atlantis-gcp%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by tekanaid** [comment]
terraform plan

**Comment by samgabrail** [comment]
Did you mean to use `atlantis` instead of `terraform`?

**Comment by tekanaid** [comment]
atlantis plan

**Comment by samgabrail** [comment]
Ran Plan for dir: `.` workspace: `default`

<details><summary>Show Output</summary>

```diff
google_compute_instance.default: Refreshing state... [id=projects/terraformprojects-365816/zones/us-central1-a/instances/atlantis-vm-dev]

Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create

Terraform will perform the following actions:

  # google_compute_instance.default will be created
+ resource "google_compute_instance" "default" {
      + can_ip_forward       = false
      + cpu_platform         = (known after apply)
      + current_status       = (known after apply)
      + deletion_protection  = false
      + guest_accelerator    = (known after apply)
      + id                   = (known after apply)
      + instance_id          = (known after apply)
      + label_fingerprint    = (known after apply)
      + machine_type         = "e2-micro"
      + metadata_fingerprint = (known after apply)
      + min_cpu_platform     = (known after apply)
      + name                 = "atlantis-vm-dev"
      + project              = (known after apply)
      + self_link            = (known after apply)
      + tags                 = [
          + "dev",
          + "engineering",
        ]
      + tags_fingerprint     = (known after apply)
      + zone                 = "us-central1-a"

      + boot_disk {
          + auto_delete                = true
          + device_name                = (known after apply)
          + disk_encryption_key_sha256 = (known after apply)
          + kms_key_self_link          = (known after apply)
          + mode                       = "READ_WRITE"
          + source                     = (known after apply)

          + initialize_params {
              + image  = "projects/ubuntu-os-cloud/global/images/ubuntu-2204-jammy-v20221014"
              + labels = {
                  + "env" = "dev"
                }
              + size   = (known after apply)
              + type   = (known after apply)
            }
        }

      + network_interface {
          + ipv6_access_type   = (known after apply)
          + name               = (known after apply)
          + network            = "default"
          + network_ip         = (known after apply)
          + stack_type         = (known after apply)
          + subnetwork         = (known after apply)
          + subnetwork_project = (known after apply)

          + access_config {
              + nat_ip       = (known after apply)
              + network_tier = (known after apply)
            }
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

* :arrow_forward: To **apply** this plan, comment:
    * `atlantis apply -d .`
* :put_litter_in_its_place: To **delete** this plan click [here](https://6cf5-20-232-211-174.ngrok.io/lock?id=samgabrail%252Fenv0-atlantis-gcp%252F.%252Fdefault)
* :repeat: To **plan** this project again, comment:
    * `atlantis plan -d .`
</details>
Plan: 1 to add, 0 to change, 0 to destroy.

---
* :fast_forward: To **apply** all unapplied plans from this pull request, comment:
    * `atlantis apply`
* :put_litter_in_its_place: To delete all plans and locks for the PR, comment:
    * `atlantis unlock`

**Comment by tekanaid** [comment]
atlantis apply

**Review by samgabrail — APPROVED** [review]
Looks good

**Comment by samgabrail** [comment]
Locks and plans deleted for the projects and workspaces modified in this pull request:

- dir: `.` workspace: `default`

**Pull request merged**
